EZS-1393: Fixed select location js error making it impossible to change the location
ezsystems/content-on-the-fly-prototype-bundle pull request #25
Opened 2017-02-22 08:01 UTC by sunpietro

https://jira.ez.no/browse/EZS-1393

2017-02-22 08:04 UTC, dew326 approved these changes

2017-02-22 08:17 UTC, micszo approved these changes
Retest OK. 👍

2017-02-22 09:38 UTC, andrerom commented
Will this break 1.7? /cc @dpobel

2017-02-22 09:41 UTC, sunpietro commented
@andrerom I agree with you. It will be the safest option.

2017-02-22 13:48 UTC, andrerom commented
@sunpietro There are two options:
A. You somehow feature detect if this is 1.7 or 1.8, allowing us to support both with same code base _(if not to hard to do, this is my personal preference)_
B. We bump version to 0.2.x and require platform ui 1.8 in this PR, branch out 0.1.x and marking it as non compatible with platform ui 1.8+, and basically will need to instruct 1.8 users to upgrade their content on the fly bundle manually as it is currently set to only install 0.1.x updates

2017-02-22 13:51 UTC, sunpietro commented
@andrerom the issue was introduced with the latest release of PlatformUI (it introduced a new version of UDW component). This fix applies to PlatformUI 1.8+.
Previous versions were not affected by the issue.

2017-02-22 14:45 UTC, dew326 commented
>A. You somehow feature detect if this is 1.7 or 1.8, allowing us to support both with same code base (if not to hard to do, this is my personal preference)

@sunpietro I think it can be done by passing some flag like `forceVisibleMethod` (feel free to use a better name) instead of `visibleMethod` and then in the plugin for the `universalDiscoveryView` on event `activeChange` we should detect if `methods` contains `browse` or `finder`.

2017-02-23 07:58 UTC, sunpietro commented
ping @dew326 
@andrerom  The newest fix proposal should keep the compatibility with both versions: 1.7 and 1.8

2017-02-23 08:03 UTC, dew326 requested changes

2017-02-23 08:03 UTC, dew326 commented on bundle/Resources/public/js/views/plugins/cof-createcontent-universaldiscoveryplugin.js
> +                this.set('visibleMethod', 'finder');
one method should be always set. If `browse` view exists the `browse` method should be set. 
And also I think we should reset the `forceVisibleMethod`, I don't know if this flag will stay when the UDW is opened again.

2017-02-23 08:29 UTC, andrerom approved these changes

2017-02-23 08:33 UTC, micszo requested changes
I suppose I have to test this again and on two versions this time. :P I put my +1 on hold and set this to request changes until done.

2017-02-23 08:46 UTC, micszo commented
1.8 retest OK.

2017-02-23 08:56 UTC, micszo commented
1.7 retest OK.

2017-02-23 09:00 UTC, micszo commented
1.8 retest OK.

2017-02-23 09:00 UTC, micszo approved these changes
It works on both versions now. 🎉

2017-02-23 09:05 UTC, dew326 approved these changes

2017-02-23 10:34 UTC, merged

2017-02-23 10:35 UTC, andrerom commented
Thanks all :)

@yannickroger / @adib78  I'll tag rc1 and send to QA, they might ask for updated meta tags.