[WIP]
ezsystems/content-on-the-fly-prototype-bundle pull request #34
Opened 2017-06-09 11:37 UTC by mnocon

2017-07-04 12:09 UTC, mnocon commented
@micszo This should be ready for review (together with PlatformUI and StudioUI PRs). I'll ask Vidar to create another jenkins job for this bundle and after approval will rerun it a few times (5 sounds nice) to make sure they're stable.

2017-07-05 09:36 UTC, andrerom approved these changes

2017-07-07 10:18 UTC, micszo approved these changes
This looks really good! 💪

2017-07-07 10:18 UTC, micszo commented on bundle/Features/Context/ContentOnTheFlyPopup.php
> +     * @param $contentType
Missing phpdoc?

2017-07-07 10:18 UTC, micszo commented on bundle/Features/Context/ContentOnTheFlyPopup.php
> +     * @param $button
Doc?

2017-07-07 10:18 UTC, micszo commented on bundle/Features/Context/ContentOnTheFlyPopup.php
> +     * @param $location
Doc?

2017-07-07 10:18 UTC, micszo commented on bundle/Features/Context/ContentOnTheFlyPopup.php
> +     * @param $location
Doc?

2017-07-07 11:06 UTC, kamilmusial requested changes

2017-07-07 11:06 UTC, kamilmusial commented on bundle/Features/Context/ContentOnTheFlyContext.php
> +     * @Given I create :contentType from :contentGroup group in :location location
PHPDoc.

2017-07-07 11:06 UTC, kamilmusial commented on bundle/Features/Context/ContentOnTheFlyContext.php
> +    public function chooseContentType($contentGroup, $contentType)
doc.

2017-07-07 11:06 UTC, kamilmusial commented on bundle/Features/Context/ContentOnTheFlyContext.php
> +    public function chooseContentType($contentGroup, $contentType)
here and below (no more comments on that)

2017-07-07 11:06 UTC, kamilmusial commented on bundle/Features/Context/ContentOnTheFlyPopup.php
> +    /** @var string Location selected by the user (defaults to /Home) */
If the default is `/Home` you can set it here.

2017-07-07 11:06 UTC, kamilmusial commented on bundle/Features/Context/ContentOnTheFlyPopup.php
> +            case 'Dashboard':
Since you don't create a separated parent registry (there's no need here) I'd put those in an associative array and then this method would like simply:
```
if (!array_key_exists($parentLocation, $this->parentLocations) {
    throw new \InvalidArgumentException('Unsupported parent location: ' . $parentLocation);
}

return $this->parentLocations[$parentLocation];
```

You can get rid of `switch` and adding a new parents will take one line instead of new `case`.

2017-07-07 11:06 UTC, kamilmusial commented on bundle/Features/Context/ContentOnTheFlyPopup.php
> +     * @return string Selector selector of the element
`@throws \InvalidArgumentException`

+ please add a newline between different doc tags.

2017-07-07 11:06 UTC, kamilmusial commented on bundle/Features/Context/ContentOnTheFlyPopup.php
> +        $this->mainSelector = "{$parentSelector} {$this->mainSelector}";
`$this->mainSelector = $parentSelector . ' ' . $this->mainSelector;`
or
`$this->mainSelector = sprintf('%s %s', $parentSelector, $this->mainSelector);`
 to keep consistency with the bundle.

Here and below.

2017-07-07 11:06 UTC, kamilmusial commented on bundle/Features/Context/ContentOnTheFlyPopup.php
> +     * @param $parentSelector Selector of the element contaning Content Of The Fly in it
`$parentSelector` type missing.

2017-07-07 11:06 UTC, kamilmusial commented on bundle/Features/Context/ContentOnTheFlyPopup.php
> +     * @param $contentGroup
Missing type (here and in other places).

2017-07-07 11:06 UTC, kamilmusial commented on bundle/Features/Context/ContentOnTheFlyPopup.php
> +        \PHPUnit_Framework_Assert::assertSame($this->selectedContentType, $selectedContentType->getText());
Please omit trailing backslash and set `use` for consistency.

2017-07-10 14:12 UTC, mnocon commented on bundle/Features/Context/ContentOnTheFlyContext.php
> +    public function chooseContentType($contentGroup, $contentType)
Added PHPDoc (and variable types) as suggested

2017-07-10 14:12 UTC, mnocon commented on bundle/Features/Context/ContentOnTheFlyPopup.php
> +    /** @var string Location selected by the user (defaults to /Home) */
Thanks, changed

2017-07-10 14:12 UTC, mnocon commented on bundle/Features/Context/ContentOnTheFlyPopup.php
> +        $this->mainSelector = "{$parentSelector} {$this->mainSelector}";
Changed everywhere to the second version.

2017-07-10 14:12 UTC, mnocon commented on bundle/Features/Context/ContentOnTheFlyPopup.php
> +            case 'Dashboard':
Thanks, this is a really cool suggestion

2017-07-10 14:12 UTC, mnocon commented on bundle/Features/Context/ContentOnTheFlyPopup.php
> +        \PHPUnit_Framework_Assert::assertSame($this->selectedContentType, $selectedContentType->getText());
Done

2017-07-11 06:43 UTC, kamilmusial approved these changes

2017-07-18 09:46 UTC, mnocon commented
@andrerom - could you merge please? The tests have been added to Jenkins and are passing, there is no work left here.

2017-07-19 13:28 UTC, merged