Fix EZP-27541: Unable to change language in embed content create view
ezsystems/content-on-the-fly-prototype-bundle pull request #36
Opened 2017-07-19 11:50 UTC by adamwojs

> JIRA: https://jira.ez.no/browse/EZP-27541

# Description

This PR adds the ability to change the language in content created via content-on-the-fly module. Code based on https://github.com/ezsystems/PlatformUIBundle/blob/master/Resources/public/js/views/services/ez-contentcreateviewservice.js#L134:L198 

# Steps to reproduce
1. Create an article. In French for example
2. In the Body field, click on + button contextual menu in the editor and choose Embed.
3. Click on Create tab, choose any content type, a location and click on Confirm selection button.
4. When the create mode of the future embedded content type appears, nothing happens when click on change language to switch the language.

2017-07-19 12:18 UTC, dew326 requested changes

2017-07-19 12:18 UTC, dew326 commented on bundle/Resources/public/js/views/plugins/cof-createcontent-universaldiscoveryserviceplugin.js
> +            this.get('host').get('app').fire('languageSelect', {
You can store `host` in the variable to not invoke `this.get('host')` multiple times. You can do the same in `_setLanguage` method.

2017-07-19 12:18 UTC, dew326 commented on bundle/Resources/public/js/views/plugins/cof-createcontent-universaldiscoveryserviceplugin.js
> +            this.fire('notify', {
As far as I know, you cannot `fire` from the plugin. You have to fire on `this.get('host')`.

2017-07-19 12:26 UTC, dew326 commented on bundle/Resources/public/js/views/plugins/cof-createcontent-universaldiscoveryserviceplugin.js
> +            this.get('host').get('app').fire('languageSelect', {
Also, the doc is missing for the `fire` methods. 

You can check here how it should look like https://github.com/ezsystems/content-on-the-fly-prototype-bundle/blob/master/bundle/Resources/public/js/views/cof-contentcreationview.js#L301

2017-07-21 12:22 UTC, adamwojs commented
PR updated with changes suggested by @dew326 comments and additional fixes of two bugs that I found:

* Visible other action than "Publish" after a language change in embedded create content form
* Changed language is not remembered after closing of embedded create content form

2017-07-21 12:52 UTC, dew326 approved these changes

2017-07-21 12:55 UTC, dew326 commented
@micszo @mnocon I think you can start testing.

2017-07-24 06:45 UTC, micszo commented
@dew326 I will cover this today 🙂

2017-07-24 07:04 UTC, sunpietro requested changes

2017-07-24 07:04 UTC, sunpietro commented on bundle/Resources/public/js/views/cof-contentcreationview.js
> +            createContentView.after('versionChange', function () {
Convert this callback function into a _protected_ method of the view. Add missing description and name it accordingly in a meaningful way.

2017-07-24 07:04 UTC, sunpietro commented on bundle/Resources/public/js/views/plugins/cof-createcontent-universaldiscoveryserviceplugin.js
> +        _selectLanguage: function (e) {
Please, follow the convention of naming event object as `event` instead of `e`

2017-07-24 07:04 UTC, sunpietro commented on bundle/Resources/public/js/views/plugins/cof-createcontent-universaldiscoveryserviceplugin.js
> +         * @param e {Object} event facade
Missing `@protected` declaration

2017-07-24 07:04 UTC, sunpietro commented on bundle/Resources/public/js/views/plugins/cof-createcontent-universaldiscoveryserviceplugin.js
> +         * changeLanguage event handler. It opens languageSelectionBox for selecting
The description can be simplified.
`Opens the LanguageSelectionBox view instance that allows to select a created content language.`

2017-07-24 07:04 UTC, sunpietro commented on bundle/Resources/public/js/views/plugins/cof-createcontent-universaldiscoveryserviceplugin.js
> +             * @param config {object} the configuration of language selection box
The config properties should be described as well.

2017-07-24 07:04 UTC, sunpietro commented on bundle/Resources/public/js/views/plugins/cof-createcontent-universaldiscoveryserviceplugin.js
> +         * @private
`@protected` 
Making it private is a bit misleading in the context of YUI views.

2017-07-24 07:04 UTC, sunpietro commented on bundle/Resources/public/js/views/plugins/cof-createcontent-universaldiscoveryserviceplugin.js
> +         * @param {Y.eZ.View} view the view which triggered language selection box
Please, follow the convention: `@param <param-name> <param-type> <param-description>`

2017-07-24 07:04 UTC, sunpietro commented on bundle/Resources/public/js/views/plugins/cof-createcontent-universaldiscoveryserviceplugin.js
> +                    languageSelectedHandler: Y.bind(this._setLanguage, this, e.target, e.fields),
Please, use native binding: `this._setLanguage.bind(this, event.target, event.fields)`

2017-07-24 07:04 UTC, sunpietro commented on bundle/Resources/public/js/views/plugins/cof-createcontent-universaldiscoveryserviceplugin.js
> +            app.fire('notify', {
Missing event doc.

2017-07-24 09:08 UTC, micszo commented
Retest OK! 
But final retest will be needed when remarks from Piotr are addressed. 🙂 
Also @adamwojs please rebase with current master as we have added some automated tests for PRs in this bundle lately.

2017-07-24 12:19 UTC, micszo commented
@adamwojs would it be possible to rebase with latest changes?

2017-07-24 12:26 UTC, adamwojs commented
@micszo It's ready ;-)

2017-07-24 13:05 UTC, micszo approved these changes
Retest OK! 👍

2017-07-24 13:09 UTC, sunpietro requested changes
Almost done. Just one small change and we're there :)

2017-07-24 13:09 UTC, sunpietro commented on bundle/Resources/public/js/views/plugins/cof-createcontent-universaldiscoveryserviceplugin.js
> +         * @param fields {Object}
Missing description

2017-07-24 13:48 UTC, sunpietro approved these changes
Please, combine all commits into one commit.

2017-07-24 14:26 UTC, merged