EZP-28713: Create using content-on-the-fly is not respecting current language
ezsystems/content-on-the-fly-prototype-bundle pull request #41
Opened 2018-01-18 09:45 UTC by adamwojs

> JIRA: https://jira.ez.no/browse/EZP-28713

## Description

This PR contains patch for not respected current language when user is creating content via content-on-the-fly

## Steps to reproduce

> 1. Create new language in admin panel via PlatformUI
> 2. Create new content using this new language
> 3. Try to embed a content in RichText field by creating another content
> 4. Notice that default language of embedded content doesn't match its parents

2018-01-18 11:32 UTC, lserwatka commented
@micszo we will need a round of QA, it is a CR.

2018-01-18 11:34 UTC, sunpietro requested changes

2018-01-18 11:34 UTC, sunpietro commented on bundle/Resources/public/js/views/plugins/cof-createcontent-universaldiscoveryserviceplugin.js
> +            if (host.get('request').params.languageCode) {
It could be stored in a variable like `var requestParams = host.get('request').params;`. That's a small perf optimisation.

2018-01-18 11:34 UTC, sunpietro commented on bundle/Resources/public/js/views/plugins/cof-createcontent-universaldiscoveryserviceplugin.js
> +            languageCode = mainLanguageCode;
I would remove the `mainLanguageCode` variable and set `type.get('mainLanguageCode')` as the value of `languageCode` variable.

2018-01-18 12:51 UTC, dew326 requested changes

2018-01-18 12:51 UTC, dew326 commented on bundle/Resources/public/js/views/plugins/cof-createcontent-universaldiscoveryserviceplugin.js
> +                languageCode = host.get('request').params.languageCode;
The request is not the best place to take the language code. You should get it from `ContentCreateViewService` or `ContentEditViewService` depending if you are in edit or create mode. The current language code is in the attr `languageCode` see: https://github.com/ezsystems/PlatformUIBundle/blob/master/Resources/public/js/views/services/ez-contentcreateviewservice.js#L179

2018-02-13 08:22 UTC, adamwojs commented
PR updated according to @sunpietro, @dew326 suggestions.

2018-02-13 08:30 UTC, dew326 approved these changes
Just a small nitpick but in general +1

2018-02-13 08:30 UTC, dew326 commented on bundle/Resources/public/js/views/plugins/cof-createcontent-universaldiscoveryserviceplugin.js
> +                activeViewService = host.get('app').get('activeViewService'),
You can create a variable `app = host.get('app')` and use it here and above for `user`. Small perf optimization.

2018-02-14 10:00 UTC, andrerom approved these changes

2018-02-14 10:00 UTC, andrerom commented
@adamwojs could you please send to QA?

2018-02-14 10:01 UTC, adamwojs commented
@andrerom Done.

2018-02-14 10:12 UTC, merged

2018-02-14 10:13 UTC, andrerom commented
Merged and tagged as part of 0.1.12-rc1 for testing with 1.13.1-rc1